# file: C:\Users\micha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\core\_exceptions.py
# hypothesis_version: 6.138.15

[1000, 1024, 'EiB', 'GiB', 'KiB', 'MiB', 'PiB', 'TiB', 'bytes', '{:#.0f} {}', '{:#.3g} {}', '{:.0f} {}', '{} ']